### ISSUE TITLE
checkpoints of pre-training

### ISSUE THREAD

**Issue by GrimaceLittleBoss** [ma-xu/Rewrite-the-Stars#4]
Thank you for your excellent work! Could you please provide the checkpoints of pre-training?

**Comment by ma-xu** [comment]
@GrimaceLittleBoss Sorry for late reply from Github. Besides the s4 checkpoints I sent via email, I uploaded all checkpoints  and logs for StarNet and included in the model python file. You can directly load via "pretrained=True".

Thanks for your interest, please feel free to let me know if any other questions or concerns.

Best,
Xu
