### ISSUE TITLE
Any ablation study on both DWConv?

### ISSUE THREAD

**Issue by whjdark** [ma-xu/Rewrite-the-Stars#5]
I'm curious about the impact of both DWConv that processes spatial information? is there any ablation study on them? use both DWConv, only pre-DWConv, only post-DWConv, or none of them. Thanks.

**Comment by ma-xu** [comment]
Hi, currently no such ablation study. 

Both conv will certainly improve the performance. Also, at least one conv op is required for spatial interaction.

**Comment by whjdark** [comment]
Thanks for answering, I will try similar ablation.
